# Wuhan-Hu-1 "reference" spike protein
ref_spike: YP_009724390

# components of parent vaccine
parent_spikes:
  # EPI_ISL_16835403 is first US XBB.1.16 isolate:
  # https://github.com/cov-lineages/pango-designation/issues/1723/
  # which has this spike protein accession:
  # https://www.ncbi.nlm.nih.gov/protein/2440446690
  XBB.1.16: WCM02109
  
# total number of components per cocktail
components_per_cocktail: 5

# mutations per design in cocktails
mutations_per_design:
  cocktail: 4
  aggressive-cocktail: 6
  conservative-cocktail: 2

# escape calculator settings, taken from specific commit indicated, which uses XBB as the "parent".
escapecalculator:
  module_url: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-escape-calc/683abdd4c3277a3cbc20cddd7ab98ff844f9ef80/escapecalculator.py
  kwargs:
    antibody_ic50s: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-escape-calc/683abdd4c3277a3cbc20cddd7ab98ff844f9ef80/results/antibody_IC50s.csv
    antibody_binding: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-escape-calc/683abdd4c3277a3cbc20cddd7ab98ff844f9ef80/results/antibody_binding.csv
    antibody_sources: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-escape-calc/683abdd4c3277a3cbc20cddd7ab98ff844f9ef80/results/antibody_sources.csv
    antibody_reweighting: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-escape-calc/683abdd4c3277a3cbc20cddd7ab98ff844f9ef80/results/antibody_reweighting.csv
    config: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-escape-calc/683abdd4c3277a3cbc20cddd7ab98ff844f9ef80/config.yaml
  parent_existing_mut_sites:
    # existing mutated sites in RBD for each parent relative to XBB
    XBB.1.16: [478]
